#include"Motorsteuerung.h"

void MotorInit_and_Mux(){
	//initailise motor
//	EHRPWMinitForDCMotor();

	// mux motor pin
	PinMuxing(CONF_H_BRUECKE_MOTOR1_1,PULL_DISABLE,0,6);
	PinMuxing(CONF_H_BRUECKE_MOTOR1_2,PULL_DISABLE,0,6);

	PinMuxing(CONF_H_BRUECKE_MOTOR2_1,PULL_DISABLE,0,4);
	PinMuxing(CONF_H_BRUECKE_MOTOR2_2,PULL_DISABLE,0,4);
}

void MotorSpeedSet(int speed){

	if(speed > 100){speed = 100;}
	if(speed < -100){speed = -100;}



	if(speed >= 0){

		EHRPWMsetDutyCycle(SOC_EPWM_1_REGS,speed);
		EHRPWMsetDutyCycle(SOC_EPWM_2_REGS,speed);

		configEHRPWM_A(SOC_EPWM_1_REGS,EHRPWM_SET_OUTPUT_HIGH,EHRPWM_SET_OUTPUT_LOW);
		configEHRPWM_B(SOC_EPWM_1_REGS,EHRPWM_SET_OUTPUT_LOW,EHRPWM_SET_OUTPUT_LOW);

		configEHRPWM_A(SOC_EPWM_2_REGS,EHRPWM_SET_OUTPUT_LOW,EHRPWM_SET_OUTPUT_LOW);
		configEHRPWM_B(SOC_EPWM_2_REGS,EHRPWM_SET_OUTPUT_HIGH,EHRPWM_SET_OUTPUT_LOW);
		// forward

	}

	if(speed < 0){
		speed = -speed;
		EHRPWMsetDutyCycle(SOC_EPWM_1_REGS,speed);
		EHRPWMsetDutyCycle(SOC_EPWM_2_REGS,speed);

		configEHRPWM_A(SOC_EPWM_1_REGS,EHRPWM_SET_OUTPUT_LOW,EHRPWM_SET_OUTPUT_LOW);
		configEHRPWM_B(SOC_EPWM_1_REGS,EHRPWM_SET_OUTPUT_HIGH,EHRPWM_SET_OUTPUT_LOW);

		configEHRPWM_A(SOC_EPWM_2_REGS,EHRPWM_SET_OUTPUT_HIGH,EHRPWM_SET_OUTPUT_LOW);
		configEHRPWM_B(SOC_EPWM_2_REGS,EHRPWM_SET_OUTPUT_LOW,EHRPWM_SET_OUTPUT_LOW);
		//reverse

	}

}


void MotorLinks(int curren_speed){
	EHRPWMsetDutyCycle(SOC_EPWM_1_REGS,15);
	EHRPWMsetDutyCycle(SOC_EPWM_2_REGS,curren_speed + 15);

	configEHRPWM_A(SOC_EPWM_1_REGS,EHRPWM_SET_OUTPUT_HIGH,EHRPWM_SET_OUTPUT_LOW);
	configEHRPWM_B(SOC_EPWM_1_REGS,EHRPWM_SET_OUTPUT_LOW,EHRPWM_SET_OUTPUT_LOW);

	configEHRPWM_A(SOC_EPWM_2_REGS,EHRPWM_SET_OUTPUT_LOW,EHRPWM_SET_OUTPUT_LOW);
	configEHRPWM_B(SOC_EPWM_2_REGS,EHRPWM_SET_OUTPUT_HIGH,EHRPWM_SET_OUTPUT_LOW);
	// forward

	delay_ms(160);

	EHRPWMsetDutyCycle(SOC_EPWM_1_REGS,curren_speed);
	EHRPWMsetDutyCycle(SOC_EPWM_2_REGS,curren_speed);
}

void MotorRechts(int curren_speed){
	EHRPWMsetDutyCycle(SOC_EPWM_1_REGS,curren_speed + 15);
	EHRPWMsetDutyCycle(SOC_EPWM_2_REGS,15);

	configEHRPWM_A(SOC_EPWM_1_REGS,EHRPWM_SET_OUTPUT_HIGH,EHRPWM_SET_OUTPUT_LOW);
	configEHRPWM_B(SOC_EPWM_1_REGS,EHRPWM_SET_OUTPUT_LOW,EHRPWM_SET_OUTPUT_LOW);

	configEHRPWM_A(SOC_EPWM_2_REGS,EHRPWM_SET_OUTPUT_LOW,EHRPWM_SET_OUTPUT_LOW);
	configEHRPWM_B(SOC_EPWM_2_REGS,EHRPWM_SET_OUTPUT_HIGH,EHRPWM_SET_OUTPUT_LOW);
	// forward

	delay_ms(160);

	EHRPWMsetDutyCycle(SOC_EPWM_1_REGS,curren_speed);
	EHRPWMsetDutyCycle(SOC_EPWM_2_REGS,curren_speed);
}

void LinkRad_RehctsRad(int speedlinks, int speedrechts){

	EHRPWMsetDutyCycle(SOC_EPWM_1_REGS,speedlinks);
	EHRPWMsetDutyCycle(SOC_EPWM_2_REGS,speedrechts);

	configEHRPWM_A(SOC_EPWM_1_REGS,EHRPWM_SET_OUTPUT_HIGH,EHRPWM_SET_OUTPUT_LOW);
	configEHRPWM_B(SOC_EPWM_1_REGS,EHRPWM_SET_OUTPUT_LOW,EHRPWM_SET_OUTPUT_LOW);

	configEHRPWM_A(SOC_EPWM_2_REGS,EHRPWM_SET_OUTPUT_LOW,EHRPWM_SET_OUTPUT_LOW);
	configEHRPWM_B(SOC_EPWM_2_REGS,EHRPWM_SET_OUTPUT_HIGH,EHRPWM_SET_OUTPUT_LOW);


}

